[package]
name = "day1"
version = "0.1.0"
authors = ["Will Kahn-Greene <willkg@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
